---
title: "CodeBook.md"
output: html_document
---

This code book describes the variables, the data, and the work that was performed to clean up the data. The data that are being cleaned are from this site: 
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 

####The Data Files
The dataset has the following .txt files: 

- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30 (number of subjects).

- 'test/subject_test.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30 (number of subjects).

####The Variables
The variables included in the datasets described above are as follows:

#####Activity labels
There are 6 activities that are performed by each of the 30 subjects. 

1 WALKING

2 WALKING_UPSTAIRS

3 WALKING_DOWNSTAIRS

4 SITTING

5 STANDING

6 LAYING

#####Features
There are 561 features. Due to the length of the list, they are not replicated here, but the reader is referred to the features.txt file. A short list is shown here, where XYZ represents the 3 axes that are represented in the larger features set. The features consist of various maesures, including the mean and std. Features are normalized and bounded within [-1,1].
The units used for the accelerations (total and body) are 'g's (gravity of earth -> 9.80665 m/sec2).The gyroscope units are rad/seg.

* tBodyAcc-XYZ
* tGravityAcc-XYZ
* tBodyAccJerk-XYZ
* tBodyGyro-XYZ
* tBodyGyroJerk-XYZ
* tBodyAccMag
* tGravityAccMag
* tBodyAccJerkMag
* tBodyGyroMag
* tBodyGyroJerkMag
* fBodyAcc-XYZ
* fBodyAccJerk-XYZ
* fBodyGyro-XYZ
* fBodyAccMag
* fBodyAccJerkMag
* fBodyGyroMag
* fBodyGyroJerkMag
